package cursortab

func languageFromExtension(ext string) string {
	lm := map[string]string{
		".ts":    "typescript",
		".tsx":   "typescriptreact",
		".js":    "javascript",
		".jsx":   "javascriptreact",
		".py":    "python",
		".cpp":   "cpp",
		".c":     "c",
		".h":     "cpp",
		".hpp":   "cpp",
		".cs":    "csharp",
		".java":  "java",
		".go":    "go",
		".rs":    "rust",
		".rb":    "ruby",
		".php":   "php",
		".swift": "swift",
		".kt":    "kotlin",
		".scala": "scala",
		".dart":  "dart",
		".r":     "r",
		".sh":    "shell",
		".bash":  "shell",
		".zsh":   "shell",
		".fish":  "shell",
		".ps1":   "powershell",
		".psm1":  "powershell",
		".sql":   "sql",
		".vue":   "vue",
		".html":  "html",
		".css":   "css",
		".scss":  "scss",
		".less":  "less",
		".json":  "json",
		".xml":   "xml",
		".yaml":  "yaml",
		".yml":   "yaml",
		".md":    "markdown",
		".lua":   "lua",
		".m":     "objective-c",
		".mm":    "objective-c",
		".f90":   "fortran",
		".f95":   "fortran",
		".f03":   "fortran",
		".f08":   "fortran",
		".jl":    "julia",
		".ex":    "elixir",
		".exs":   "elixir",
		".elm":   "elm",
		".fs":    "fsharp",
		".fsx":   "fsharp",
		".pl":    "perl",
		".pm":    "perl",
		".hs":    "haskell",
		".lhs":   "haskell",
		".clj":   "clojure",
		".cljs":  "clojure",
		".erl":   "erlang",
		".hrl":   "erlang",
	}

	l, ok := lm[ext]
	if !ok {
		return "plaintext"
	}

	return l
}

// this is taken from the workbench source code
/*
return (
    {
      ".ts": "typescript",
      ".tsx": "typescriptreact",
      ".js": "javascript",
      ".jsx": "javascriptreact",
      ".py": "python",
      ".cpp": "cpp",
      ".c": "c",
      ".h": "cpp",
      ".hpp": "cpp",
      ".cs": "csharp",
      ".java": "java",
      ".go": "go",
      ".rs": "rust",
      ".rb": "ruby",
      ".php": "php",
      ".swift": "swift",
      ".kt": "kotlin",
      ".scala": "scala",
      ".dart": "dart",
      ".r": "r",
      ".sh": "shell",
      ".bash": "shell",
      ".zsh": "shell",
      ".fish": "shell",
      ".ps1": "powershell",
      ".psm1": "powershell",
      ".sql": "sql",
      ".vue": "vue",
      ".html": "html",
      ".css": "css",
      ".scss": "scss",
      ".less": "less",
      ".json": "json",
      ".xml": "xml",
      ".yaml": "yaml",
      ".yml": "yaml",
      ".md": "markdown",
      ".lua": "lua",
      ".m": "objective-c",
      ".mm": "objective-c",
      ".f90": "fortran",
      ".f95": "fortran",
      ".f03": "fortran",
      ".f08": "fortran",
      ".jl": "julia",
      ".ex": "elixir",
      ".exs": "elixir",
      ".elm": "elm",
      ".fs": "fsharp",
      ".fsx": "fsharp",
      ".pl": "perl",
      ".pm": "perl",
      ".hs": "haskell",
      ".lhs": "haskell",
      ".clj": "clojure",
      ".cljs": "clojure",
      ".erl": "erlang",
      ".hrl": "erlang",
    }[e] || "plaintext"
  );
*/
